version: '3.8'

name: mernapp

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mernapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mernapp
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: npm run dev  # ✅ This is good if your Dockerfile doesn't override it

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mernapp
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev  # ✅ Safe if CMD is defined in Dockerfile too

volumes:
  mongo_data:

networks:
  mernapp:
    driver: bridge
