version: '3.8'

name: mernapp

services:
    mongo:
        image: mongo:6
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - mernapp

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile 
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - mernapp
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        command: npm run dev
        
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - mernapp
        command: npm run dev
        ports:
            - "5173:5173"
        depends_on:
            - backend

volumes:
    mongo_data:

networks:
    mernapp:
        driver: bridge

    
